// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-HyFGDH9n4VY4fznSoISgQX8CbFOiGQU',
    appId: '1:495417203478:web:ee2ae599c9e4005d350e37',
    messagingSenderId: '495417203478',
    projectId: 'coffe-db-auth',
    authDomain: 'coffe-db-auth.firebaseapp.com',
    storageBucket: 'coffe-db-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfrx9I411cYydxuA_TdhGyLPKjIsXWmZU',
    appId: '1:495417203478:android:45a158e54d3be28a350e37',
    messagingSenderId: '495417203478',
    projectId: 'coffe-db-auth',
    storageBucket: 'coffe-db-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPJKuvNmnnkFGrnZ2E7zxqOc8gZXTgurg',
    appId: '1:495417203478:ios:b6e3de62ff758f10350e37',
    messagingSenderId: '495417203478',
    projectId: 'coffe-db-auth',
    storageBucket: 'coffe-db-auth.appspot.com',
    iosClientId: '495417203478-iqgqimu3dp42a5g1ch3veb5s0m12pn1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPJKuvNmnnkFGrnZ2E7zxqOc8gZXTgurg',
    appId: '1:495417203478:ios:b6e3de62ff758f10350e37',
    messagingSenderId: '495417203478',
    projectId: 'coffe-db-auth',
    storageBucket: 'coffe-db-auth.appspot.com',
    iosClientId: '495417203478-iqgqimu3dp42a5g1ch3veb5s0m12pn1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeProject',
  );
}
